# Generated by Django 3.1.1 on 2020-09-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('iID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('1', 'middle school'), ('2', 'high school'), ('3', 'college'), ('4', 'bootcamp'), ('5', 'other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('subject', models.TextField()),
                ('iID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.institution')),
            ],
        ),
    ]
